imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'VichUploaderBundle:Form:fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        logging: true

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        filters:
            published: AppBundle\Doctrine\PublishedFilter

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        images:
            uri_prefix:         /uploads/images
            upload_destination: "%kernel.root_dir%/../web/uploads/images"
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        albums:
            uri_prefix:         /uploads/images
            upload_destination: "%kernel.root_dir%/../web/uploads/albums"
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true

easy_admin:
    formats:
            date:     'd. m. Y'
            time:     'H:i'
            datetime: 'd. m. Y - H:i:s'
            number: '%.2f'
    design:
        form_theme: 'vertical'
        menu:
            - { entity: 'FrontPage', icon: 'user', label: 'Artists' }
            - { entity: 'Album', icon: 'music', label: 'Albums' }
            - { entity: 'Donations', icon: 'money', label: 'Donations' }
            - { label: 'Translation', url: '/admin/trans', icon: 'language' }
        assets:
            js:
                - '/bundles/app/js/vich.js'
                - '/assets/vendor/color-thief/dist/color-thief.js'
                - '/assets/vendor/imagesloaded.imagesloaded.pkgd.min.js'
                - '/bundles/app/js/field-type.js'
            css:
                - '/bundles/app/css/fields.css'
    entities:
        FrontPage:
            class: AppBundle\Entity\FrontPage
            label: Artists
            list:
                fields:
                    - { property: 'id', label: 'ID', type: 'integer' }
                    - { property: 'url', label: 'URL', type: 'url' }
                    - { property: 'name', label: 'Name', type: 'string' }
                    - { property: 'albums', label: 'Albums', type: 'association' }
                    - { property: 'public', label: 'Public', type: 'wtoggle' }
            form:
                fields:
                    - { property: 'name', type: 'text', label: 'Name', css_class: 'col-lg-3' }
                    - { property: 'shortName', type: 'text', label: 'Short Name', css_class: 'col-lg-3' }
                    - { property: 'location', type: 'text', label: 'Location', css_class: 'col-lg-3' }
                    - { property: 'genre', type: 'text', label: 'Genre', css_class: 'col-lg-3' }
                    - { property: 'UURL', type: 'text', label: 'UURL', css_class: 'col-lg-12', type_options: {attr: {pattern: "^[.a-zA-Z0-9-]+$"}} }
                    - { property: 'image', type: 'AppBundle\Form\ImageType', label: 'Image', css_class: 'col-lg-6' }
                    - { property: 'cover', type: 'AppBundle\Form\ImageType', label: 'Cover', css_class: 'col-lg-6' }
                    - { property: 'video', type: 'text', label: 'Video URL (relative to web/)', css_class: 'col-lg-6' }
                    - { property: 'vita', type: 'ckeditor', label: 'Vita' }
                    - { property: 'metaDescription', type: 'text', label: 'Meta - Description (160 Chars)' }
                    - { property: 'citations', type: 'ckeditor', label: 'Citations (One per <em>)' }
                    - { property: 'links', type: 'collection', label: 'Links', type_options: { entry_options: { label: false }, entry_type: AppBundle\Form\LinkType, attr: { class: 'field-links' } }}
                    - { property: 'public', type: 'checkbox', label: 'Public', css_class: 'col-lg-12' }
        Album:
            class: AppBundle\Entity\Album
            list:
                fields:
                    - { property: 'id', label: 'ID', type: 'integer' }
                    - { property: 'title', label: 'Title', type: 'string' }
                    - { property: 'artist', label: 'Aritst Name', type: 'string' }
                    - { property: 'public', label: 'Public', type: 'toggle' }
                    - { property: 'downloads', label: 'Downloads', type: 'integer', format: '%d' }
            form:
                fields:
                    - { property: 'title', type: 'text', label: 'Title' }
                    - { property: 'cover', type: 'AppBundle\Form\ImageType', label: 'Cover', css_class: 'col-lg-12' }
                    - { property: 'backgroundColor', type: 'text', label: 'Background Color', css_class: 'col-lg-3', type_options: { attr: { class: 'field-background' } } }
                    - { property: 'primaryColor', type: 'text', label: 'Primary Color', css_class: 'col-lg-3', type_options: { attr: { class: 'field-primary' } } }
                    - { property: 'secondaryColor', type: 'text', label: 'Secondary Color', css_class: 'col-lg-3', type_options: { attr: { class: 'field-secondary' } } }
                    - { property: 'description', type: 'ckeditor', label: 'Description' }
                    - { property: 'UURL', type: 'text', label: 'UURL', type_options: {attr: {pattern: "^[.a-zA-Z0-9-]+$"}} }
                    - { property: 'soundcloud', type: 'text', label: 'SoundCloud' }
                    - { property: 'published', type: 'date', label: 'Published' }
                    - { property: 'frontPage', label: 'Artist Profile' }
                    - { property: 'albumFilePath', type: 'text' ,label: 'Download File path' }
                    - { property: 'public', type: 'checkbox', label: 'Public', css_class: 'col-lg-12' }
        Donations:
            class: AppBundle\Entity\Donation
            list:
                fields:
                    - { property: 'id', label: 'ID', type: 'integer' }
                    - { property: 'date', label: 'Date', type: 'date', format: 'Y/m/d' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'floatAmount', label: 'Amount', type: 'text' }
            form:
                fields:
                    - { property: 'date', label: 'Date', type: 'date' }
                    - { property: 'email', label: 'Email', type: 'text' }
                    - { property: 'amount', label: 'Amount', type: 'money' }
    site_name: 'keingrenzen.org Backend'

jms_i18n_routing:
    default_locale: de
    locales: [de] #  locales: [de, en, fr]
    strategy: prefix_except_default
    use_cookie: false

jms_translation:
    configs:
        app:
            dirs: ["%kernel.root_dir%/", "%kernel.root_dir%/../src/"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            ignored_domains: [routes]
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            extractors: [jms_i18n_routing]

ivory_ck_editor:
    default_config: default
    configs:
        default:
            toolbar: basic
