parameters:
    database_host: db623538632.db.1and1.com
    database_port: null
    database_name: db623538632
    database_user: dbo623538632
    database_password: BNn3itqVbLwk/UN5QQ5lyg==
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 79d5aae618f37b605bb21f6f4f8f6ba658f95f10